Oracles + Interop Contract
phantasma-io/phantasma-ng pull request #260
Opened 2023-05-31 16:20 UTC by TeknoPT

## Please do not open any `Pull Requests` to the `master` branch. 
## If you do so expect them to be closed without further notice.

## `Pull Requests` are very weclome on the `development` branch.

Thank you.

2023-06-06 12:59 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/InteropContract.cs
> +        private BigInteger MinimumFeePercentage = 0;
Can be made constant. Change name to match constant style.

2023-06-06 14:17 UTC, IngloriousBasterd99 commented on Phantasma.Infrastructure/src/API/NexusAPI.cs
> +    private static PhantasmaKeys _keys { get; set; }
Change to be a private field, rather than private properly. Properties are normally reserved for public.

2023-06-06 14:17 UTC, IngloriousBasterd99 commented on Phantasma.Infrastructure/src/API/NexusAPI.cs
> +    public static void SetKey(PhantasmaKeys Key)
Key should be camel case

2023-06-06 14:17 UTC, IngloriousBasterd99 commented on Phantasma.Infrastructure/src/API/NexusAPI.cs
> +        string result = "";
Apply code formatting.

2023-06-06 14:24 UTC, IngloriousBasterd99 approved these changes

2023-06-06 14:27 UTC, IngloriousBasterd99 requested changes
See inline comments.

2023-06-06 14:59 UTC, TeknoPT commented on Phantasma.Business/src/Blockchain/Contracts/Native/InteropContract.cs
> +        private BigInteger MinimumFeePercentage = 0;
Big Integer's can't be used as const.

2023-06-06 23:29 UTC, IngloriousBasterd99 requested changes

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/Bet.cs
> +}
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/CrossChainTransfer.cs
> +
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/InteropHistory.cs
> +}
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/InteropWithdraw.cs
> +}
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/PlatformDetails.cs
> +
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/PlatformTokens.cs
> +
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/Swapper.cs
> +
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-06 23:29 UTC, IngloriousBasterd99 commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/TokenSwapToSwap.cs
> +
Public fields are uncommon. Public member variables should be properties, and their names should be Pascal case.

2023-06-07 08:11 UTC, TeknoPT commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/PlatformTokens.cs
> +
They're using PascalCase

2023-06-12 06:26 UTC, TeknoPT commented on Phantasma.Business/src/Blockchain/Contracts/Native/InteropContract.cs
> +        private BigInteger MaximumFeePercentage = 10;
Big int's can't be a const.

2023-06-12 06:28 UTC, TeknoPT commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/InteropHistory.cs
> +}
In this case i can't change them.

2023-06-12 06:28 UTC, TeknoPT commented on Phantasma.Business/src/Blockchain/Contracts/Native/Interop/InteropWithdraw.cs
> +}
In this case i can't change them.

2023-06-19 09:10 UTC, merged